//
//  SentenceGenerator.swift
//  SillyWords
//
//  Created by Ben Roaman on 8/23/26.
//

import Foundation
import BRWordGeneration

struct SentenceGenerator {
    private init() { }
    @MainActor private static var currentPool: Set<BRSentence> = fullPool
    
    static func useItInASentence(_ word: String) -> String {
        if currentPool.isEmpty {
            currentPool = fullPool
        }
        
        let sentence = currentPool.randomElement() ?? fallbackSentence
        currentPool.remove(sentence)
        
        return sentence.insert(word: word)
    }
    
    private static let fallbackSentence = BRSentence(format: "Please us %@ in a sentence.",
                                                     plural: false,
                                                     properNoun: false,
                                                     firstWord: false)
    
    private static let fullPool: Set<BRSentence> = [
        BRSentence(format: "I can see your %@.",
                 plural: nil,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "That's the biggest %@ I've ever seen!",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "The %@ is pungent today.",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "He fell and scraped his %@.",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "Have you seen the new %@?",
                 plural: false,
                 properNoun: true,
                 firstWord: false),
        BRSentence(format: "I watch the %@ every night.",
                 plural: nil,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "Where do you get your %@ from?",
                 plural: nil,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "Why does that %@ always get in my way?",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "Cheryl, that cat left another %@ at our door.",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "%@, am I right?",
                 plural: nil,
                 properNoun: false,
                 firstWord: true),
        BRSentence(format: "Does it smell like %@ in here?",
                 plural: nil,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "The %@ really is beautiful in autumn.",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "You know I heard she got a %@ job.",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "What's the deal with %@?",
                 plural: nil,
                 properNoun: nil,
                 firstWord: false),
        BRSentence(format: "Ach! I keep tripping over that %@!",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "I was climbing a fence and snagged my %@.",
                 plural: nil,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "That darn %@ is always underfoot!",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "Why does that %@ look so shiny?",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "Is the %@ supposed to get wet?",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "They have %@ now?!",
                 plural: true,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "All your %@ are belong to us.",
                 plural: true,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "Mr. %@ is my favorite teacher.",
                 plural: false,
                 properNoun: true,
                 firstWord: false),
        BRSentence(format: "I hear %@ is beautiful this time of year.",
                 plural: false,
                 properNoun: true,
                 firstWord: false),
        BRSentence(format: "That's my pet snake %@, she's my best friend.",
                 plural: false,
                 properNoun: true,
                 firstWord: false),
        BRSentence(format: "Why do they have so many %@?",
                 plural: true,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "Look up! The trees are full of %@!",
                 plural: nil,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "Put. Down. The %@.",
                 plural: nil,
                 properNoun: nil,
                 firstWord: false),
        BRSentence(format: "Is the %@ supposed quiver like that?",
                 plural: false,
                 properNoun: nil,
                 firstWord: false),
        BRSentence(format: "And now I'm covered in %@.",
                 plural: nil,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "You can't handle the %@!",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "It's like %@ on your wedding day.",
                 plural: false,
                 properNoun: false,
                 firstWord: false),
        BRSentence(format: "How many %@ are you going to eat?",
                 plural: true,
                 properNoun: false,
                 firstWord: false),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
        //        BRSentence(format: <#T##String#>,
        //                 plural: <#T##Bool?#>,
        //                 properNoun: <#T##Bool#>,
        //                 firstWord: <#T##Bool#>),
    ]
}
